### ISSUE TITLE
I2C to UART Expansion IO

### ISSUE THREAD

**Issue by JasonPittenger** [m5stack/M5Unit-EXTIO2#2]
Can we add support for additional UART ports?
Can this be used as an I2C to UART converter?

On the STM32F03F4P6 used in the device:
Pins 6/7 are USART4_TX/RX.
Pins 8/9 are USART2_TX/RX.
Pins 10/11 are USART6_TX/RX.
Maybe pins 12/13 can be a low speed bit-bang UART?

**Comment by TinyuZhao** [comment]
In fact we have open sourced the [firmware](https://github.com/m5stack/M5Unit-EXTIO2-Internal-FW) and we applaud the fact that there are no plans to make it support UART communication, if you want to try it, you are welcome to ask us for a PR.
