### ISSUE TITLE
Adding a More Efficient Digital I/O interface

### ISSUE THREAD

**Issue by JasonPittenger** [m5stack/M5Unit-EXTIO2#4]
I saw that setting all 8 digital outputs requires 8 separate I2C transactions.  
I also saw that reading all 9 digital inputs requires 8 separate I2C transactions.

I suggest adding two more registers to allow setting/reading all 8 I/O in one I2C transaction.
Register 0x18 can be used to directly translate the data byte into bits for the 8 outputs.
b0 = IO0, b1 = IO1, b2 = IO2 etc.
When using register 0x18, the bit for any pin not set to DIGITAL_OUTPUT_MODE would be ignored.
Register 0x28 can be used to encode the status of the inputs into one data byte.
b0 = IO0, b1 = IO1, b2 = IO2 etc.
When using register 0x28, the bit for any pin not set to DIGITAL_INPUT_MODE would always return 0.

Making this change can speed up I/O operations by as much as 8x or reduce I2C traffic to 1/8th.

I created a fork on both this code and on the internal firmware code that implements these new registers.
I have also created a pull request to merge this into the code.

**Comment by TinyuZhao** [comment]
👍
https://github.com/m5stack/M5Unit-EXTIO2/commit/e123f193767bfafb3345c069fb2f97740ce3c1d2
