### ISSUE TITLE
1.0.2 now show in library manager

### ISSUE THREAD

**Issue by burner-** [m5stack/M5Unit-EXTIO2#6]
Some reason adruino library manager show only 1.0.1 version but not 1.0.2

**Comment by TinyuZhao** [comment]
I have not found this problem.
<img width="798" alt="image" src="https://user-images.githubusercontent.com/44396641/233685794-25a3a52c-80ac-4817-be05-bc1a6725ac65.png">

**Comment by burner-** [comment]
Hmm now it find it... Thats odd. Anyways looks that even 1.0.2 does not support setPinMode as git version does. Can you publish 1.0.3 from current git version?

**Comment by TinyuZhao** [comment]
> Hmm now it find it... Thats odd. Anyways looks that even 1.0.2 does not support setPinMode as git version does. Can you publish 1.0.3 from current git version?

OK，I will publish it.

**Comment by TinyuZhao** [comment]
Released.
https://github.com/m5stack/M5Unit-EXTIO2/commit/e123f193767bfafb3345c069fb2f97740ce3c1d2
