### ISSUE TITLE
[Q] SPI support

### ISSUE THREAD

**Issue by eadmaster** [m5stack/M5Unit-EXTIO2#7]
can this be used for SPI communication,  to connect modules like a CC1101:
https://github.com/gramaziokohler/clamp_electronics/blob/master/doc/radio/CC1101_Radio.md

If not, is there any official M5stack module that supports that?

**Comment by TinyuZhao** [comment]
SPI communication cannot be used.
may be you need is product https://docs.m5stack.com/en/unit/uhf_rfid
